// Autogenerated embedded catalog fallback for Vercel Serverless deployments
export const INITIAL_CATEGORIES = [
  {
    "id": "9e635a86-affe-4f4a-9110-65ce699daa66",
    "slug": "hoodies",
    "nameEn": "Hoodies & Sweatshirts",
    "nameAr": "الهوديات والسويت شيرت",
    "descriptionEn": "Heavyweight cotton oversized hoodies imported from Turkey.",
    "descriptionAr": "هوديات قطن ثقيل أوفرسايز صُنعت في تركيا.",
    "image": "https://images.unsplash.com/photo-1556905055-8f358a7a47b2?q=80&w=1000&auto=format&fit=crop",
    "order": 1,
    "isHidden": false,
    "createdAt": "2026-09-07T15:50:30.071Z"
  },
  {
    "id": "70101b99-8473-4d74-a38b-293219f14e7c",
    "slug": "tshirts",
    "nameEn": "T-Shirts & Oversized",
    "nameAr": "التيشيرتات والأوفرسايز",
    "descriptionEn": "Drop-shoulder street tees with high-density graphics.",
    "descriptionAr": "تيشيرتات أكتاف منسدلة وطباعة عالية الدقة.",
    "image": "https://images.unsplash.com/photo-1521572267360-ee0c2909d518?q=80&w=1000&auto=format&fit=crop",
    "order": 2,
    "isHidden": false,
    "createdAt": "2026-09-07T15:50:30.076Z"
  },
  {
    "id": "a3cd6180-a0a1-46ad-ab4b-8f9323f47f12",
    "slug": "pants",
    "nameEn": "Pants & Cargo",
    "nameAr": "البناطيل والكارغو",
    "descriptionEn": "Tactical cargo pants and relaxed streetwear trousers.",
    "descriptionAr": "بناطيل كارغو تكتيكية وقصات ستريت وير مريحة.",
    "image": "https://images.unsplash.com/photo-1624378439575-d8705ad7ae80?q=80&w=1000&auto=format&fit=crop",
    "order": 3,
    "isHidden": false,
    "createdAt": "2026-09-07T15:50:30.080Z"
  },
  {
    "id": "b85a4604-56d7-41ee-b1e1-b0f0c14bc865",
    "slug": "sneakers",
    "nameEn": "Sneakers & Shoes",
    "nameAr": "الأحذية والسنيكرز",
    "descriptionEn": "Premium luxury sneakers and chunky street silhouettes.",
    "descriptionAr": "سنيكرز فاخرة وقصات متميزة للشارع.",
    "image": "https://images.unsplash.com/photo-1552346154-21d32810aba3?q=80&w=1000&auto=format&fit=crop",
    "order": 4,
    "isHidden": false,
    "createdAt": "2026-09-07T15:50:30.085Z"
  },
  {
    "id": "030d18f2-3701-42a0-9dd4-70131213d0b3",
    "slug": "caps",
    "nameEn": "Caps & Accessories",
    "nameAr": "القبعات والإكسسوارات",
    "descriptionEn": "Embroidered dad hats, beanies, and silver jewelry.",
    "descriptionAr": "قبعات مطرزة، طواقي، وإكسسوارات أنيقة.",
    "image": "https://images.unsplash.com/photo-1588850561407-ed78c282e89b?q=80&w=1000&auto=format&fit=crop",
    "order": 5,
    "isHidden": false,
    "createdAt": "2026-09-07T15:50:30.090Z"
  }
];

const rawProductsData = [
  {
    "id": "156ac7b7-8cbc-4d98-97c1-09a53614c24f",
    "slug": "oversized-black-island-hoodie",
    "nameEn": "BLACK ISLAND Signature Heavy Hoodie",
    "nameAr": "هودي بلاك آيلاند قطن ثقيل أوفرسايز",
    "descEn": "Premium 500GSM 100% Turkish cotton fleece. Features dropped shoulders, double-layered hood, and minimal embroidered logo on the chest. Built for winter performance in Damascus.",
    "descAr": "مصنع من قطن تركي 100% بسمك 500 غرام. أكتاف منسدلة، طاقية مضاعفة، وتطريز بشعار بلاك آيلاند الفاخر على الصدر.",
    "price": 380000,
    "salePrice": 320000,
    "sku": "BI-HD-001",
    "featured": true,
    "isNew": true,
    "isSale": true,
    "isActive": true,
    "categorySlug": "hoodies",
    "createdAt": "2026-09-07T15:50:30.096Z",
    "updatedAt": "2026-09-07T15:50:30.096Z",
    "images": [
      {
        "id": "3c0cdeaf-7245-4938-a300-b69025347f75",
        "productId": "156ac7b7-8cbc-4d98-97c1-09a53614c24f",
        "url": "https://images.unsplash.com/photo-1556905055-8f358a7a47b2?q=80&w=1000&auto=format&fit=crop",
        "isMain": true,
        "order": 0
      },
      {
        "id": "4d46b4fc-d7f4-46e3-b75d-d4b10140f686",
        "productId": "156ac7b7-8cbc-4d98-97c1-09a53614c24f",
        "url": "https://images.unsplash.com/photo-1509967419530-da38b4704bc6?q=80&w=1000&auto=format&fit=crop",
        "isMain": false,
        "order": 1
      }
    ],
    "variants": [
      {
        "id": "d7b443d8-e58b-489e-82f2-32db4b43631d",
        "productId": "156ac7b7-8cbc-4d98-97c1-09a53614c24f",
        "size": "S",
        "colorName": "Obsidian Black",
        "colorHex": "#000000",
        "colorImage": null,
        "colorImages": null,
        "stock": 15
      },
      {
        "id": "18e47d8b-d023-4f99-aa57-23744a63dc56",
        "productId": "156ac7b7-8cbc-4d98-97c1-09a53614c24f",
        "size": "M",
        "colorName": "Obsidian Black",
        "colorHex": "#000000",
        "colorImage": null,
        "colorImages": null,
        "stock": 25
      },
      {
        "id": "66941417-2668-4bb2-9140-6af49779a314",
        "productId": "156ac7b7-8cbc-4d98-97c1-09a53614c24f",
        "size": "L",
        "colorName": "Obsidian Black",
        "colorHex": "#000000",
        "colorImage": null,
        "colorImages": null,
        "stock": 20
      },
      {
        "id": "a99ee9bd-92cb-4a08-a20f-5b2089b70358",
        "productId": "156ac7b7-8cbc-4d98-97c1-09a53614c24f",
        "size": "XL",
        "colorName": "Obsidian Black",
        "colorHex": "#000000",
        "colorImage": null,
        "colorImages": null,
        "stock": 10
      },
      {
        "id": "93fd0948-657a-4fc0-9bc1-33b73536f495",
        "productId": "156ac7b7-8cbc-4d98-97c1-09a53614c24f",
        "size": "XXL",
        "colorName": "Obsidian Black",
        "colorHex": "#000000",
        "colorImage": null,
        "colorImages": null,
        "stock": 5
      },
      {
        "id": "aa669488-ee7f-4683-bdcc-e5a65ae4fa17",
        "productId": "156ac7b7-8cbc-4d98-97c1-09a53614c24f",
        "size": "M",
        "colorName": "Charcoal Gray",
        "colorHex": "#262626",
        "colorImage": null,
        "colorImages": null,
        "stock": 18
      }
    ]
  },
  {
    "id": "e2f7b8a1-4321-4d98-88b1-12a53614c250",
    "slug": "acid-wash-vintage-tee",
    "nameEn": "BLACK ISLAND Vintage Acid Wash Tee",
    "nameAr": "تيشيرت فنتج غسيل حمضي اوفرسايز",
    "descEn": "Custom 280GSM heavy jersey. Unique hand-finished acid wash technique. Relaxed boxy streetwear fit.",
    "descAr": "قطن ثقيل 280 غرام مع معالجة غسيل حمضي فنتج وفاخرة. قصات واسعة مريحة.",
    "price": 180000,
    "salePrice": null,
    "sku": "BI-TS-002",
    "featured": true,
    "isNew": true,
    "isSale": false,
    "isActive": true,
    "categorySlug": "tshirts",
    "createdAt": "2026-09-07T15:50:30.100Z",
    "updatedAt": "2026-09-07T15:50:30.100Z",
    "images": [
      {
        "id": "5e0cdeaf-8245-4938-a300-b69025347f76",
        "productId": "e2f7b8a1-4321-4d98-88b1-12a53614c250",
        "url": "https://images.unsplash.com/photo-1521572267360-ee0c2909d518?q=80&w=1000&auto=format&fit=crop",
        "isMain": true,
        "order": 0
      }
    ],
    "variants": [
      {
        "id": "e8b443d8-e58b-489e-82f2-32db4b43631e",
        "productId": "e2f7b8a1-4321-4d98-88b1-12a53614c250",
        "size": "M",
        "colorName": "Vintage Grey",
        "colorHex": "#4a4a4a",
        "colorImage": null,
        "colorImages": null,
        "stock": 20
      },
      {
        "id": "f8b443d8-e58b-489e-82f2-32db4b43631f",
        "productId": "e2f7b8a1-4321-4d98-88b1-12a53614c250",
        "size": "L",
        "colorName": "Vintage Grey",
        "colorHex": "#4a4a4a",
        "colorImage": null,
        "colorImages": null,
        "stock": 15
      }
    ]
  },
  {
    "id": "f3a8c9b2-5432-4e09-99c2-23b64725d361",
    "slug": "tactical-cargo-pants-black",
    "nameEn": "Tactical Multi-Pocket Cargo Pants",
    "nameAr": "بنطال كارغو تكتيكي جيوب متعددة",
    "descEn": "Heavy-duty ripstop cotton blend. 6 functional utility pockets, adjustable ankle cuffs, and reinforced knees.",
    "descAr": "مصنوع من قطن تكتيكي مقاوم مع 6 جيوب عملية وتطريز متين عند الركبتين.",
    "price": 290000,
    "salePrice": 240000,
    "sku": "BI-PT-003",
    "featured": true,
    "isNew": false,
    "isSale": true,
    "isActive": true,
    "categorySlug": "pants",
    "createdAt": "2026-09-07T15:50:30.110Z",
    "updatedAt": "2026-09-07T15:50:30.110Z",
    "images": [
      {
        "id": "6f0cdeaf-9245-4938-a300-b69025347f77",
        "productId": "f3a8c9b2-5432-4e09-99c2-23b64725d361",
        "url": "https://images.unsplash.com/photo-1624378439575-d8705ad7ae80?q=80&w=1000&auto=format&fit=crop",
        "isMain": true,
        "order": 0
      }
    ],
    "variants": [
      {
        "id": "g9b443d8-e58b-489e-82f2-32db4b436320",
        "productId": "f3a8c9b2-5432-4e09-99c2-23b64725d361",
        "size": "30",
        "colorName": "Black",
        "colorHex": "#000000",
        "colorImage": null,
        "colorImages": null,
        "stock": 10
      },
      {
        "id": "h9b443d8-e58b-489e-82f2-32db4b436321",
        "productId": "f3a8c9b2-5432-4e09-99c2-23b64725d361",
        "size": "32",
        "colorName": "Black",
        "colorHex": "#000000",
        "colorImage": null,
        "colorImages": null,
        "stock": 12
      },
      {
        "id": "i9b443d8-e58b-489e-82f2-32db4b436322",
        "productId": "f3a8c9b2-5432-4e09-99c2-23b64725d361",
        "size": "34",
        "colorName": "Black",
        "colorHex": "#000000",
        "colorImage": null,
        "colorImages": null,
        "stock": 8
      }
    ]
  },
  {
    "id": "a4b9d0c3-6543-4f10-00d3-34c75836e472",
    "slug": "black-island-hyper-sneaker-01",
    "nameEn": "BLACK ISLAND Luxury Chunky Sneaker",
    "nameAr": "سنيكرز بلاك آيلاند جلد طبيعي فاخر",
    "descEn": "Crafted in Turkey with premium full-grain Italian leather accents, high-density shock-absorbing outsole, and metallic gold logo branding.",
    "descAr": "صُنع في تركيا من الجلد الطبيعي الفاخر، نعل ممتص للصدمات وشعار بلاك آيلاند الذهبي.",
    "price": 450000,
    "salePrice": 390000,
    "sku": "BI-SN-004",
    "featured": true,
    "isNew": true,
    "isSale": true,
    "isActive": true,
    "categorySlug": "sneakers",
    "createdAt": "2026-09-07T15:50:30.120Z",
    "updatedAt": "2026-09-07T15:50:30.120Z",
    "images": [
      {
        "id": "7g0cdeaf-0245-4938-a300-b69025347f78",
        "productId": "a4b9d0c3-6543-4f10-00d3-34c75836e472",
        "url": "https://images.unsplash.com/photo-1552346154-21d32810aba3?q=80&w=1000&auto=format&fit=crop",
        "isMain": true,
        "order": 0
      }
    ],
    "variants": [
      {
        "id": "j0c554e9-f69c-490f-93f3-43ec5b547433",
        "productId": "a4b9d0c3-6543-4f10-00d3-34c75836e472",
        "size": "41",
        "colorName": "Obsidian White",
        "colorHex": "#ffffff",
        "colorImage": null,
        "colorImages": null,
        "stock": 5
      },
      {
        "id": "k0c554e9-f69c-490f-93f3-43ec5b547434",
        "productId": "a4b9d0c3-6543-4f10-00d3-34c75836e472",
        "size": "42",
        "colorName": "Obsidian White",
        "colorHex": "#ffffff",
        "colorImage": null,
        "colorImages": null,
        "stock": 7
      },
      {
        "id": "l0c554e9-f69c-490f-93f3-43ec5b547435",
        "productId": "a4b9d0c3-6543-4f10-00d3-34c75836e472",
        "size": "43",
        "colorName": "Obsidian White",
        "colorHex": "#ffffff",
        "colorImage": null,
        "colorImages": null,
        "stock": 4
      }
    ]
  }
];

export const INITIAL_PRODUCTS: any[] = rawProductsData.map((p) => ({
  ...p,
  category: INITIAL_CATEGORIES.find((c) => c.slug === p.categorySlug) || {
    id: 'cat-default',
    slug: p.categorySlug,
    nameEn: p.categorySlug,
    nameAr: p.categorySlug,
    descriptionEn: '',
    descriptionAr: '',
    image: '',
    order: 1,
    isHidden: false,
    createdAt: new Date().toISOString(),
  },
}));
