import { PrismaClient } from '@prisma/client';
import fs from 'fs';
import path from 'path';

const dbPath = path.join(process.cwd(), 'prisma', 'dev_backup.db');
const prisma = new PrismaClient({ datasources: { db: { url: `file:${dbPath}` } } });

async function exportCatalog() {
  const categories = await prisma.category.findMany({ orderBy: { order: 'asc' } });
  const products = await prisma.product.findMany({
    include: {
      images: { orderBy: { order: 'asc' } },
      variants: true,
      category: true,
    },
    orderBy: { createdAt: 'desc' },
  });

  const catalogContent = `// Autogenerated embedded catalog fallback with ALL ${products.length} user-uploaded products & ${categories.length} categories
export const INITIAL_CATEGORIES = ${JSON.stringify(categories, null, 2)};

export const INITIAL_PRODUCTS: any[] = ${JSON.stringify(products, null, 2)};
`;

  fs.writeFileSync(path.join(process.cwd(), 'src/lib/initialCatalog.ts'), catalogContent);
  console.log(`Successfully updated initialCatalog.ts with ${products.length} products and ${categories.length} categories!`);

  // Also update prisma/dev.db
  fs.copyFileSync(path.join(process.cwd(), 'prisma/dev_backup.db'), path.join(process.cwd(), 'prisma/dev.db'));
  console.log('Successfully restored prisma/dev.db with full catalog!');
}

exportCatalog();
